from tkinter import *
from tkinter import ttk
import tkinter as tk
import tkintermapview as tmap
import time
import os
########
root=Tk()
root.resizable(width=False, height=False)
root.title('SPVTransit')
root.configure(bg='white')
root.state('zoomed')
global scr_w
scr_w=root.winfo_screenwidth()
global scr_h
scr_h=root.winfo_screenheight()
root.geometry(str(scr_w)+'x'+str(scr_h))
########
def permission():
    if str(user.get())=='STUPAR':
        userbox.delete(0, len(str(userbox.get())))
        userbox.insert(END, '#Name of Parent')
    elif str(user.get())=='ATTEN':
        userbox.delete(0, len(str(userbox.get())))
        userbox.insert(END, '#Name of Attendant')
    elif str(user.get())=='ADMIN':
        userbox.delete(0, len(str(userbox.get())))
        userbox.insert(END, '#Admin Username')
def linked():
    #code for connecting databases and verification if the data inputted by the user matches up with the record stored in the tables.
    canvas.delete("all")
    canvas.create_window(350,100, window=tableselect)
    canvas.pack()
    canvas.create_window(260,150, window=PV)
    canvas.pack()
    if str(user.get())=='STUPAR':
        canvas.create_window(260,200, window=lengthlabel)
        canvas.pack()
        lengthbox.insert(END, '#value from table')
        lengthbox['state']='disabled'
        canvas.create_window(260,220, window=lengthbox)
        canvas.pack()
        canvas.create_window(260,260, window=stopslabel)
        canvas.pack()
        stopsbox.insert(END, '#value from table')
        stopsbox['state']='disabled'
        canvas.create_window(260,280, window=stopsbox)
        canvas.pack()
        canvas.create_window(260,320, window=capacitylabel)
        canvas.pack()
        capacitybox.insert(END, '#value from table')
        capacitybox['state']='disabled'
        canvas.create_window(260,340, window=capacitybox)
        canvas.pack()
def routechange(event):
    PV['text']=str(table.get())
    canvas.update()
    canvas.pack()
########
canvas=Canvas(root, width=scr_w, height=scr_h, bg='white')
logoimg=PhotoImage(file='logoimage.png')
canvas.create_image(640,250, image=logoimg)
canvas.pack()
permit=ttk.Label(canvas, text="<WELCOME! YOU ARE:>", font=('Courier New',13), background='white')
canvas.create_window(240,450, window=permit)
canvas.pack()
user=StringVar()
stupar=tk.Radiobutton(canvas, text='A Student/Parent', font=('Courier New',11),variable=user, value='STUPAR', bg='white', command=permission)
canvas.create_window(240,480, window=stupar)
canvas.pack()
atten=tk.Radiobutton(canvas, text='An Attendant', font=('Courier New',11),variable=user, value='ATTEN', bg='white', command=permission)
canvas.create_window(222,500, window=atten)
canvas.pack()
admin=tk.Radiobutton(canvas, text='An Administrator', font=('Courier New',11),variable=user, value='ADMIN', bg='white', command=permission)
canvas.create_window(240,520, window=admin)
canvas.pack()
uname=StringVar()
passwd=StringVar()
userlabel=ttk.Label(canvas, text="<Username:>", font=('Courier New',10), background='white')
canvas.create_window(640,450, window=userlabel)
canvas.pack()
userbox=ttk.Entry(canvas, textvariable=uname, font=('Courier New',11))
canvas.create_window(640,470, window=userbox)
canvas.pack()
passlabel=ttk.Label(canvas, text="<Password:>", font=('Courier New',10), background='white')
canvas.create_window(640,500, window=passlabel)
canvas.pack()
passbox=ttk.Entry(canvas, textvariable=passwd, font=('Courier New',11), show="*")
canvas.create_window(640,520, window=passbox)
canvas.pack()
proceed=ttk.Label(canvas, text="   <Verify and \n Connect Databases:>", font=('Courier New',10), background='white')
canvas.create_window(1040,470, window=proceed)
canvas.pack()
button1=ttk.Button(canvas, text='>', command=linked)
canvas.create_window(1040,510, window=button1)
canvas.pack()
routes=[]
routes.append('<Choose a route:>')
for i in range(1,23):
    x='PV-'+str(i)
    routes.append(x)
table=StringVar()
tableselect=ttk.Combobox(canvas, textvariable=table, font=('Courier New',11))
tableselect['values']=tuple(routes)
tableselect.state(["readonly"])
tableselect.current(0)
tableselect.bind("<<ComboboxSelected>>", routechange)
PV=ttk.Label(canvas, text=str(table.get()), font=('Courier New',15), background='white')
lengthlabel=ttk.Label(canvas, text='Length:', font=('Courier New',11), background='white')
length=StringVar()
lengthbox=ttk.Entry(canvas, textvariable=length, font=('Courier New',9))
stopslabel=ttk.Label(canvas, text='Number of Stops:', font=('Courier New',11), background='white')
stops=StringVar()
stopsbox=ttk.Entry(canvas, textvariable=stops, font=('Courier New',9))
capacitylabel=ttk.Label(canvas, text='Capacity:', font=('Courier New',11), background='white')
capacity=StringVar()
capacitybox=ttk.Entry(canvas, textvariable=capacity, font=('Courier New',9))
attendantlabel=ttk.Label(canvas, text='Attendant:', font=('Courier New',11), background='white')
attendantname=StringVar()
attendantbox=ttk.Entry(canvas, textvariable=attendantname, font=('Courier New',9))
attenconlabel=ttk.Label(canvas, text='Contact:', font=('Courier New',11), background='white')
attencon=StringVar()
attenconbox=ttk.Entry(canvas, textvariable=attencon, font=('Courier New',9))
driverlabel=ttk.Label(canvas, text='Driver:', font=('Courier New',11), background='white')
drivername=StringVar()
driverbox=ttk.Entry(canvas, textvariable=drivername, font=('Courier New',9))
driverconlabel=ttk.Label(canvas, text='Contact:', font=('Courier New',11), background='white')
drivercon=StringVar()
driverconbox=ttk.Entry(canvas, textvariable=drivercon, font=('Courier New',9))
conductorlabel=ttk.Label(canvas, text='Conductor:', font=('Courier New',11), background='white')
conductorname=StringVar()
conductorbox=ttk.Entry(canvas, textvariable=conductorname, font=('Courier New',9))
conconlabel=ttk.Label(canvas, text='Contact:', font=('Courier New',11), background='white')
concon=StringVar()
conconbox=ttk.Entry(canvas, textvariable=concon, font=('Courier New',9))
PASSENGER=ttk.Label(canvas, text='Passenger Details:', font=('Courier New',15), background='white')
passidlabel=ttk.Label(canvas, text='Passenger-ID:', font=('Courier New',11), background='white')
passid=StringVar()
passidbox=ttk.Entry(canvas, textvariable=passid, font=('Courier New',9))
namelabel=ttk.Label(canvas, text='Name of Passenger:', font=('Courier New',11), background='white')
name=StringVar()
namebox=ttk.Entry(canvas, textvariable=name, font=('Courier New',9))
passpwdlabel=ttk.Label(canvas, text='Password:', font=('Courier New',11), background='white')
passpwd=StringVar()
passpwdbox=ttk.Entry(canvas, textvariable=passpwd, font=('Courier New',9))
phonelabel=ttk.Label(canvas, text='Phone Number:', font=('Courier New',11), background='white')
phone=StringVar()
phonebox=ttk.Entry(canvas, textvariable=phone, font=('Courier New',9))
routelabel=ttk.Label(canvas, text='Route:', font=('Courier New',11), background='white')
route=StringVar()
routebox=ttk.Entry(canvas, textvariable=route, font=('Courier New',9))
stoplabel=ttk.Label(canvas, text='Stop:', font=('Courier New',11), background='white')
stop=StringVar()
stopbox=ttk.Entry(canvas, textvariable=stop, font=('Courier New',9))
########
root.mainloop()

